from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.pam_task_detail import PamTaskDetail
from openapi_server import util

from openapi_server.models.pam_task_detail import PamTaskDetail  # noqa: E501

class AccessVerificationResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pam_tasks=None):  # noqa: E501
        """AccessVerificationResponse - a model defined in OpenAPI

        :param pam_tasks: The pam_tasks of this AccessVerificationResponse.  # noqa: E501
        :type pam_tasks: List[PamTaskDetail]
        """
        self.openapi_types = {
            'pam_tasks': List[PamTaskDetail]
        }

        self.attribute_map = {
            'pam_tasks': 'pamTasks'
        }

        self._pam_tasks = pam_tasks

    @classmethod
    def from_dict(cls, dikt) -> 'AccessVerificationResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccessVerificationResponse of this AccessVerificationResponse.  # noqa: E501
        :rtype: AccessVerificationResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pam_tasks(self) -> List[PamTaskDetail]:
        """Gets the pam_tasks of this AccessVerificationResponse.


        :return: The pam_tasks of this AccessVerificationResponse.
        :rtype: List[PamTaskDetail]
        """
        return self._pam_tasks

    @pam_tasks.setter
    def pam_tasks(self, pam_tasks: List[PamTaskDetail]):
        """Sets the pam_tasks of this AccessVerificationResponse.


        :param pam_tasks: The pam_tasks of this AccessVerificationResponse.
        :type pam_tasks: List[PamTaskDetail]
        """
        if pam_tasks is None:
            raise ValueError("Invalid value for `pam_tasks`, must not be `None`")  # noqa: E501

        self._pam_tasks = pam_tasks
