apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pamapi
  name: pamapi
  namespace: openunison
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pamapi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pamapi
    spec:
      containers:
      - image: harbor.qalab.tremolo.dev/lab/priv-service:latest
        imagePullPolicy: Always
        name: pamapi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        allowPrivilegedEscalation: false
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pamapi
  name: pamapi
  namespace: openunison
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pamapi
  sessionAffinity: None
  type: ClusterIP